workflows:
  ios-build:
    name: iOS Debug Build with Rust
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustc --version
          cargo --version
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
